### ISSUE TITLE
Bib File Not Found

### ISSUE THREAD

**Issue by DRManager** [crsh/citr#12]
I was able to get citr to work first time installed. However, I have an issue to load the bib file. 

The symptom is as following: it can find the bib file from YAML, but not be able to load it in the citation.

Warning: Error in RefManageR::ReadBib: lex fatal error:
fatal flex scanner internal error--end of buffer missed

![bib_issue](https://cloud.githubusercontent.com/assets/14171632/24822991/c851842c-1bae-11e7-8b63-2f112bc0b898.png)

**Comment by crsh** [comment]
Hi @DRManager, could you upload a copy of your bibliography file so I can take a closer look?

**Comment by DRManager** [comment]
Hi Frederik,

I attached the bib file exported from Zotero for reference. Could you take
a look if it is due to file format or Shiny loading issue? The bib file has been zipped for uploading purpose.

Thanks,

[SiGe.zip](https://github.com/crsh/citr/files/911779/SiGe.zip)

Richard

**Comment by crsh** [comment]
I'm still working on this. It appears that the problem is the `cited-references` field. For some references it contains a lot of content (>17000 characters). If I remove those fields the file is read fine. This is not per se a `citr`-problem but related to `bibtex::read.bib`. I'm trying to figure out a way to patch the function to avoid this problem. For now, you might want to try citr's [Zotero integration](https://github.com/crsh/citr#better-biblatex-integration) and maybe try to not export the `cited-references` field via [BetterBibTeX](https://github.com/retorquere/zotero-better-bibtex/wiki/Customized-Exports).

**Comment by crsh** [comment]
It appears there is finally some movement on this over at the [`bibtex` repository](https://github.com/romainfrancois/bibtex/issues/16). There are some suggestions on how to patch this problem until the fix is released.
