### ISSUE TITLE
Directly access Zotero via SQLite

### ISSUE THREAD

**Issue by crsh** [crsh/citr#13]
I suspect that direct access to the Zotero database via SQLite will greatly improve the speed of the database connection and may enable access to group libraries (#9). It would also remove the dependency on BetterBib(La)Tex for the Zotero integration.

**Comment by mbojan** [comment]
That would be great as BetterBib(La)TeX is not (yet) compatible with Zotero version 5 (retorquere/zotero-better-bibtex#555)   !

**Comment by retorquere** [comment]
You can only access the Zotero DB directly when Zotero is not running. It's trivial to make a plugin that would allow running queries on a running Zotero over HTTP though -- [this](https://github.com/retorquere/zotero-better-bibtex/tree/master/test/fixtures/debug-bridge) could be used as-is or tweaked easily.

**Comment by crsh** [comment]
Thanks for the suggestion, I'll look into it more closely as soon as I get a chance.

**Comment by retorquere** [comment]
(WRT BBT it's at this time more accurate to say that it's [not feature-complete](https://trello.com/b/OpJQyVTP/better-bibtex-for-zotero-5) rather than not being compatible BTW; BBT for Z4 is not compatible with Z5 and cannot be given the extensive changes between Z4 and Z5, but BBT for Z5 is of course compatible with Z5)

**Comment by crsh** [comment]
As pointed out above, it doesn't look like it's possible to access the database if Zotero is running. [As of late](https://github.com/retorquere/zotero-better-bibtex/issues/787), access to group libraries can be achieved via BBT.
