### ISSUE TITLE
citr error

### ISSUE THREAD

**Issue by koliajaykr** [crsh/citr#19]
citr:::insert_citation()
Error in `Encoding<-`(`*tmp*`, value = "UTF-8") : 
  a character vector argument expected

> sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Linux Mint 18.2

locale:
 [1] LC_CTYPE=en_IN.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_IN.UTF-8        LC_COLLATE=en_IN.UTF-8    
 [5] LC_MONETARY=en_IN.UTF-8    LC_MESSAGES=en_IN.UTF-8   
 [7] LC_PAPER=en_IN.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_IN.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] shiny_1.0.5      R6_2.2.2         assertthat_0.2.0 htmltools_0.3.6 
 [5] tools_3.2.3      rstudioapi_0.7   yaml_2.1.14      Rcpp_0.12.12    
 [9] digest_0.6.12    citr_0.2.0       xtable_1.8-2     httpuv_1.3.5    
[13] mime_0.5         miniUI_0.1.1

**Comment by crsh** [comment]
Hi Ajay, I need a little more context to understand what's going on here. Could you help me understand what's going on by describing what you did and what you behavior you expected?

**Comment by koliajaykr** [comment]
Thank you for your reply. I'm using bookdown to write my PhD thesis. For reference management I'm using Zotero 5 + Better Bibtex. But I'm not able to use the 'citr' add on of Rstudio. Citr get crashed or left with the error as mentioned in my first post. Please ask me if you need more information. Citr is very useful add on but I'm not able to use it.

**Comment by crsh** [comment]
So you are trying to access your Zotero-Library. Until yesterday there had been no official release of the Better BibLaTeX-Plugin for Zotero 5. Are you using this latest release?

**Comment by koliajaykr** [comment]
Yes, I'm using the latest Better BibLaTex-Plugin for Zotero 5. You may find this attachment useful to help me out.
![peek 2017-11-13 19-50](https://user-images.githubusercontent.com/28312545/32730310-abb64112-c8ac-11e7-9648-ca50844e8ad3.gif)

**Comment by crsh** [comment]
Interesting. Have you tried using the addin with an R Markdown or R script file open?

**Comment by crsh** [comment]
I should probably add, it looks like the API of the plug in was changed and I need to make adjustments to the code in order for it to work. If the addin loads correctly this will cause the loading of the library to never finish.

**Comment by koliajaykr** [comment]
Thank you so much friend. Just now I run a successful minimal bookdown example with citr. Let me check the same with my work too, fingers crossed.

**Comment by ak-koli** [comment]
Still citr is crashed. Please watch the attached video of rstudio.

Ajay Kumar Koli
PhD Student
School of Management Studies
University of Hyderabad, India

**Comment by ak-koli** [comment]
I'm sorry the video is not running.

Ajay Kumar Koli
PhD Student
School of Management Studies
University of Hyderabad, India

**Comment by koliajaykr** [comment]
In the context of my work, citr is still getting crashed.

![peek 2017-11-14 00-01](https://user-images.githubusercontent.com/28312545/32742655-1aa28d1a-c8d0-11e7-92fb-cbb475805821.gif)

**Comment by crsh** [comment]
It looks like we have solved your initial problem. I have also pushed a commit that should resolve the requirement to have a source editor pane open when `insert_citation()` is called.

What you are experiencing now is a different problem and related to `RefManageR::ReadBib()`. It's hard to make out from the video (it would be helpful if you could add the error message to your post) but it looks like the error message is telling you what's happening:

1. Something seems to be at odds with the ZehnerGreen... reference.
2. An author name includes a special character that the function cannot handle (`Gallop{\'\i}n`). I've seen [similar behavior](https://github.com/ropensci/RefManageR/issues/16) before. You may want to create an issue about this at the `RefManageR` repository. For a quick fix, try changing the format of that entry in your Zotero library.
3. Your library contains a technical report that is missing the institution information which is required.

It's probably not be necessary to address all of these to enable reading your Zotero library. I'd start with 2. and continue with 3. if necessary.

I'm closing this issue as this problem is unrelated to `citr`. Thanks for reaching out concerning your original issue.

**Comment by koliajaykr** [comment]
Thank you friend for your time and solutions. I corrected the references. Now citr is doing unfinished loading, as you mentioned in your earlier comment. Please see the attached screen-shot.
![screenshot from 2017-11-14 22-44-26](https://user-images.githubusercontent.com/28312545/32794047-c3cb9004-c98d-11e7-99bd-4f49005287f7.png)

**Comment by crsh** [comment]
This is due to a change in the Better BibLaTeX plugin that breaks backward compatibility. The problem has been addressed by the developer and you may install a [test build](https://github.com/retorquere/zotero-better-bibtex/issues/784) to circumvent the issue until I can supply a fix (I'll open a new issue for that).

**Comment by koliajaykr** [comment]
I'm new with many technical terms and processes here. Let me see what I can do. Thank you.
