### ISSUE TITLE
Crashes with very large Zotero libraries

### ISSUE THREAD

**Issue by bwiernik** [crsh/citr#32]
I have a very large local Zotero database (>35,000 items including top-level items, attachments, and notes). When I have the default option to use the entire Zotero library enabled, citr is unable to load. It tries for several minutes, then eventually crashes.

**Comment by crsh** [comment]
Hi there. Sorry to hear that. To further investigate the source of the problem, could you provide a copy of the `.bib`-file that `citr` tries to read? You can accesses it at http://localhost:23119/better-bibtex/library?/1/library.bibtex when Zotero is running.

**Comment by bwiernik** [comment]
I sent you the file via email

**Comment by crsh** [comment]
Okay, I was able to read that file (using the addin) without a problem. Could you try and confirm that the error persists when you use the addin to read this file (rather than your Zotero bibliography directly)? To do so you need to either close Zotero or click the `Disconnect`-action link and specify the path to the `.bib` file.

**Comment by crsh** [comment]
Also, when you say it crashes, did you get an error message? If so, could you post it here?
